name: Unity CI

on:
  push:
    branches:
      - main
permissions:
  contents: write # Dodaje uprawnienia do edycji

jobs:
  build:
    strategy:
      matrix:
        target_platform:
          ["StandaloneWindows64", "StandaloneLinux64", "StandaloneOSX"]
    name: Build Unity Project for ${{ matrix.target_platform }}
    if: ${{ startsWith(github.event.head_commit.message, '[RELEASE]') }} # Warunek sprawdzający, czy wiadomość commita zawiera fragment: [RELEASE] na początku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Cache Library
        uses: actions/cache@v4.2.2
        with:
          path: Library
          key: ${{ runner.os }}-unity-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            ${{ runner.os }}-unity-

      - name: Build Project
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.target_platform }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.4.3
        if: ${{ matrix.target_platform != 'StandaloneOSX' }} # Ignoruje MacOS dla oszczędności miejsca
        with:
          name: Build-${{ matrix.target_platform }}
          path: build

  release:
    needs: build
    name: Deploy a release
    if: ${{ startsWith(github.event.head_commit.message, '[RELEASE]') }} # Warunek sprawdzający, czy wiadomość commita zawiera fragment: [RELEASE] na początku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          path: ${{ github.workspace}}/release

      - name: Zip release
        run: |
          mv ${{ github.workspace}}/release/Build-StandaloneWindows64/* .
          zip -r Build-StandaloneWindows64.zip StandaloneWindows64
          mv ${{ github.workspace}}/release/Build-StandaloneLinux64/* .
          zip -r Build-StandaloneLinux64.zip StandaloneLinux64

      - name: Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: latest
          files: |
            Build-StandaloneWindows64.zip
            Build-StandaloneLinux64.zip
